### ISSUE TITLE
Verifying bank transfer if webhook fails

### ISSUE THREAD

**Issue by CodebyOmar** [Flutterwave/FlutterwaveV3#1]
Transactions in v3 are queried using this endpoint ```/transactions/:id/verify``` and ```id``` here is gotten from webhook payload ```data.id```. Which means if for any reason webhook fails you won't be able to directly query for the transaction and issue value to users

**Comment by jesseinit** [comment]
I've always wondered why we need to verify a transaction in the webhook? Is there any reason why this check should be required to give value to the user?

**Comment by CodebyOmar** [comment]
for payments done via bank transfers, webhook is the way to get notified when the transaction is successful.

**Comment by CodebyOmar** [comment]
After 2 months without a reply, the issue is closed without response or solution? you might as well close down the repository @Corvus97

**Comment by oyin25** [comment]
Can someone share knowledge how to code the php to be able to send FCM Notifications to user immediately user receive money from outside
