### ISSUE TITLE
POST API: https://api.flutterwave.com/v3/virtual-cards UNABLE TO GENERATE CARD

### ISSUE THREAD

**Issue by siteantipas** [Flutterwave/FlutterwaveV3#3]
[https://developer.flutterwave.com/reference#create-virtual-card](https://developer.flutterwave.com/reference#create-virtual-card)

After following the above documentation, the card still doesn't get created...even through the dashboard UI, still get the error  
**UNABLE TO GENERATE CARD**

**Comment by Corvus97** [comment]
Hello @siteantipas,

Thanks for bringing this to our attention.

Kindly retry the API call. Please ensure that you have sufficient balance to create the card before calling the endpoint.

Do feel free to reach out if you need any additional assistance.

Kind regards,
Cornelius.
